services:
  - type: web
    name: livesun-comercial
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "src.app:create_app()" --timeout 120
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: "False"
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: u951548013_LS_Comercial
      - key: SECRET_KEY
        sync: false
      - key: SESSION_TIMEOUT
        value: "3600"
      - key: DB_POOL_RECYCLE
        value: "1800"
