-- LiveSun Comercial - Schema completo (MySQL 5.7+ / 8+)
-- Ajuste o nome do database conforme necessidade.

CREATE DATABASE IF NOT EXISTS comercial
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE comercial;

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- =========================
-- CORE
-- =========================
CREATE TABLE IF NOT EXISTS empresas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE,
    cnpj VARCHAR(18) UNIQUE,
    plano VARCHAR(20) NOT NULL DEFAULT 'premium',
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NULL,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_admin TINYINT(1) NOT NULL DEFAULT 0,
    role VARCHAR(20) NOT NULL DEFAULT 'viewer',
    dashboard_chart_days INT NOT NULL DEFAULT 30,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT uq_users_empresa_username UNIQUE (empresa_id, username),
    CONSTRAINT uq_users_email UNIQUE (email),
    INDEX idx_users_empresa_id (empresa_id),
    INDEX idx_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    role VARCHAR(20) NOT NULL,
    permission_key VARCHAR(80) NOT NULL,
    allowed TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_role_permissions_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT uq_role_permission_empresa_role_key UNIQUE (empresa_id, role, permission_key),
    INDEX idx_role_permissions_empresa (empresa_id),
    INDEX idx_role_permissions_role (role),
    INDEX idx_role_permissions_key (permission_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_permission_overrides (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    user_id INT NOT NULL,
    permission_key VARCHAR(80) NOT NULL,
    allowed TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_permission_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_user_permission_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_user_permission_override UNIQUE (empresa_id, user_id, permission_key),
    INDEX idx_user_permission_empresa (empresa_id),
    INDEX idx_user_permission_user (user_id),
    INDEX idx_user_permission_key (permission_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fluxo_contas_modelo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    tipo VARCHAR(1) NOT NULL,
    mascara VARCHAR(50) NULL,
    nivel_sintetico INT NULL,
    nivel_analitico INT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_fluxo_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    INDEX idx_fluxo_empresa (empresa_id),
    INDEX idx_fluxo_codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Plano de contas padrao (ajuste o ID da empresa antes de executar)
SET @empresa_id = 1;

INSERT INTO fluxo_contas_modelo (
    empresa_id,
    codigo,
    descricao,
    tipo,
    mascara,
    nivel_sintetico,
    nivel_analitico,
    ativo,
    criado_em,
    atualizado_em
) VALUES
(@empresa_id, '1', 'Entradas de Caixa', 'R', NULL, 1, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.1', 'Receitas Operacionais', 'R', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.1.1', 'Vendas a vista', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.1.2', 'Vendas cartao credito', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.1.3', 'Vendas cartao debito', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.1.4', 'Recebimento mensalidades/servicos', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.2', 'Receitas Financeiras', 'R', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.2.1', 'Juros recebidos', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.2.2', 'Descontos obtidos', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.3', 'Outras Entradas', 'R', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.3.1', 'Emprestimos recebidos', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.3.2', 'Aporte de socios', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '1.3.3', 'Reembolsos diversos', 'R', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2', 'Saidas de Caixa', 'P', NULL, 1, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.1', 'Custos Operacionais', 'P', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.1.1', 'Compra de mercadorias', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.1.2', 'Materia-prima/insumos', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.1.3', 'Fretes sobre compras', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.2', 'Despesas Fixas', 'P', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.2.1', 'Aluguel', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.2.2', 'Energia eletrica', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.2.3', 'Agua', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.2.4', 'Internet e telefone', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.3', 'Despesas com Pessoal', 'P', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.3.1', 'Salarios', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.3.2', 'Encargos (INSS, FGTS)', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.3.3', 'Pro-labore', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.4', 'Despesas Variaveis', 'P', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.4.1', 'Comissoes sobre vendas', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.4.2', 'Taxas de cartao/maquininha', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.4.3', 'Impostos sobre vendas', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.5', 'Despesas Financeiras', 'P', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.5.1', 'Juros e multas pagas', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.5.2', 'Tarifas bancarias', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.6', 'Outras Saidas', 'P', NULL, 2, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.6.1', 'Distribuicao de lucros', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(@empresa_id, '2.6.2', 'Adiantamentos a socios', 'P', NULL, 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS contas_banco (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    banco VARCHAR(50) NOT NULL,
    agencia VARCHAR(10) NOT NULL,
    numero_conta VARCHAR(20) NOT NULL,
    dv VARCHAR(2) NULL,
    tipo VARCHAR(20) NULL,
    fluxo_conta_id INT NULL,
    saldo_inicial DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    is_principal TINYINT(1) NOT NULL DEFAULT 0,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_conta_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_conta_fluxo FOREIGN KEY (fluxo_conta_id) REFERENCES fluxo_contas_modelo(id),
    INDEX idx_conta_empresa (empresa_id),
    INDEX idx_conta_nome (nome),
    INDEX idx_conta_principal (is_principal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS entidades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    cnpj_cpf VARCHAR(18) NOT NULL,
    tipo VARCHAR(1) NULL,
    fluxo_conta_id INT NULL,
    aliquota_comissao_especifica DECIMAL(5,2) NULL,
    valor_repasse DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    vendedor_id INT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_entidades_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_entidades_fluxo_conta FOREIGN KEY (fluxo_conta_id) REFERENCES fluxo_contas_modelo(id),
    CONSTRAINT fk_entidades_vendedor FOREIGN KEY (vendedor_id) REFERENCES entidades(id),
    INDEX idx_entidades_empresa (empresa_id),
    INDEX idx_entidades_cnpj (cnpj_cpf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lancamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    data_evento DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberto',
    entidade_id INT NOT NULL,
    fluxo_conta_id INT NOT NULL,
    conta_banco_id INT NOT NULL,
    valor_real DECIMAL(15,2) NOT NULL,
    valor_pago DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_imposto DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_outros_custos DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    numero_documento VARCHAR(50) NULL,
    observacoes TEXT NULL,
    referencia_banco VARCHAR(100) NULL,
    fonte VARCHAR(50) NOT NULL DEFAULT 'manual',
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_lanc_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_lanc_entidade FOREIGN KEY (entidade_id) REFERENCES entidades(id),
    CONSTRAINT fk_lanc_fluxo FOREIGN KEY (fluxo_conta_id) REFERENCES fluxo_contas_modelo(id),
    CONSTRAINT fk_lanc_conta FOREIGN KEY (conta_banco_id) REFERENCES contas_banco(id),
    INDEX idx_lanc_empresa (empresa_id),
    INDEX idx_lanc_evento (data_evento),
    INDEX idx_lanc_vencimento (data_vencimento),
    INDEX idx_lanc_pagamento (data_pagamento),
    INDEX idx_lanc_documento (numero_documento),
    INDEX idx_lanc_referencia (referencia_banco)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fluxo_caixa_realizado (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    data DATE NOT NULL,
    fluxo_conta_id INT NOT NULL,
    conta_banco_id INT NOT NULL,
    saldo_anterior DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_pago DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_recebido DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    saldo_atual DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_fluxo_realizado_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_fluxo_realizado_fluxo FOREIGN KEY (fluxo_conta_id) REFERENCES fluxo_contas_modelo(id),
    CONSTRAINT fk_fluxo_realizado_conta FOREIGN KEY (conta_banco_id) REFERENCES contas_banco(id),
    INDEX idx_fluxo_realizado_empresa (empresa_id),
    INDEX idx_fluxo_realizado_data (data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fluxo_caixa_previsto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    data DATE NOT NULL,
    fluxo_conta_id INT NOT NULL,
    conta_banco_id INT NOT NULL,
    saldo_anterior DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_previsto_pago DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_previsto_recebido DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    saldo_previsto DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_fluxo_previsto_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_fluxo_previsto_fluxo FOREIGN KEY (fluxo_conta_id) REFERENCES fluxo_contas_modelo(id),
    CONSTRAINT fk_fluxo_previsto_conta FOREIGN KEY (conta_banco_id) REFERENCES contas_banco(id),
    INDEX idx_fluxo_previsto_empresa (empresa_id),
    INDEX idx_fluxo_previsto_data (data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS parametros_sistema (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    chave VARCHAR(100) NOT NULL,
    valor TEXT NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'string',
    descricao VARCHAR(255) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_parametros_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT uq_parametro_chave UNIQUE (empresa_id, chave),
    INDEX idx_parametro_empresa_chave (empresa_id, chave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comissoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    id_apuracao INT NOT NULL,
    lancamento_id INT NOT NULL,
    entidade_cliente_id INT NOT NULL,
    entidade_vendedor_id INT NOT NULL,
    dt_lancamento DATE NOT NULL,
    dt_vencimento DATE NOT NULL,
    dt_pagamento_recebimento DATE NOT NULL,
    vl_nota DECIMAL(15,2) NOT NULL,
    vl_imposto DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vl_outros_custos DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vl_repasse DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    vl_liquido DECIMAL(15,2) NOT NULL,
    aliquota_aplicada DECIMAL(5,2) NOT NULL,
    vl_comissao DECIMAL(15,2) NOT NULL,
    situacao VARCHAR(20) NOT NULL DEFAULT 'ativo',
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_comissoes_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_comissoes_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id),
    CONSTRAINT fk_comissoes_cliente FOREIGN KEY (entidade_cliente_id) REFERENCES entidades(id),
    CONSTRAINT fk_comissoes_vendedor FOREIGN KEY (entidade_vendedor_id) REFERENCES entidades(id),
    INDEX idx_comissoes_empresa (empresa_id),
    INDEX idx_comissoes_lancamento_data (dt_lancamento),
    INDEX idx_comissoes_vencimento (dt_vencimento),
    INDEX idx_comissoes_pagamento (dt_pagamento_recebimento),
    INDEX idx_comissoes_lancamento (lancamento_id),
    INDEX idx_comissoes_cliente (entidade_cliente_id),
    INDEX idx_comissoes_vendedor (entidade_vendedor_id),
    INDEX idx_comissao_empresa_apuracao (empresa_id, id_apuracao),
    INDEX idx_comissao_empresa_lancamento (empresa_id, lancamento_id, entidade_cliente_id, entidade_vendedor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS importacao_nfse (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    chave_nota VARCHAR(60) NOT NULL,
    numero_nota VARCHAR(30) NOT NULL,
    data_emissao DATE NOT NULL,
    cnpj_tomador VARCHAR(20) NOT NULL,
    entidade_id INT NULL,
    lancamento_id INT NULL,
    valor_bruto DECIMAL(15,2) NOT NULL,
    valor_impostos DECIMAL(15,2) NULL,
    descricao_servico TEXT NULL,
    status_importacao VARCHAR(20) NOT NULL DEFAULT 'sucesso',
    mensagem_erro VARCHAR(255) NULL,
    data_importacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endereco_rua VARCHAR(150) NULL,
    endereco_numero VARCHAR(10) NULL,
    endereco_bairro VARCHAR(100) NULL,
    endereco_cidade VARCHAR(100) NULL,
    endereco_uf VARCHAR(2) NULL,
    endereco_cep VARCHAR(8) NULL,
    telefone VARCHAR(20) NULL,
    email VARCHAR(120) NULL,
    contrato_produto TEXT NULL,
    aliquota_iss DECIMAL(5,2) NULL,
    aliquota_comissao_especifica DECIMAL(5,2) NULL,
    valor_repasse DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    entidade_vendedor_padrao_id INT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_nfse_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_nfse_entidade FOREIGN KEY (entidade_id) REFERENCES entidades(id),
    CONSTRAINT fk_nfse_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id) ON DELETE CASCADE,
    CONSTRAINT fk_nfse_vendedor_padrao FOREIGN KEY (entidade_vendedor_padrao_id) REFERENCES entidades(id),
    INDEX idx_nfse_empresa (empresa_id),
    INDEX idx_nfse_chave (chave_nota),
    INDEX idx_nfse_entidade (entidade_id),
    INDEX idx_nfse_lancamento (lancamento_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS conciliacao_bancaria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    conta_banco_id INT NOT NULL,
    periodo_inicio DATE NOT NULL,
    periodo_fim DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberta',
    observacoes TEXT NULL,
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_conciliacao_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_conciliacao_conta FOREIGN KEY (conta_banco_id) REFERENCES contas_banco(id),
    CONSTRAINT fk_conciliacao_user FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_conciliacao_empresa (empresa_id),
    INDEX idx_conciliacao_conta (conta_banco_id),
    INDEX idx_conciliacao_periodo (periodo_inicio, periodo_fim)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS conciliacao_item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    conciliacao_id INT NOT NULL,
    lancamento_id INT NULL,
    data_movimento DATE NOT NULL,
    descricao_extrato VARCHAR(255) NULL,
    referencia_banco VARCHAR(120) NULL,
    valor_extrato DECIMAL(15,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente',
    motivo_divergencia VARCHAR(255) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_conciliacao_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_conciliacao_item_conciliacao FOREIGN KEY (conciliacao_id) REFERENCES conciliacao_bancaria(id) ON DELETE CASCADE,
    CONSTRAINT fk_conciliacao_item_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id) ON DELETE SET NULL,
    INDEX idx_conciliacao_item_empresa (empresa_id),
    INDEX idx_conciliacao_item_conciliacao (conciliacao_id),
    INDEX idx_conciliacao_item_lancamento (lancamento_id),
    INDEX idx_conciliacao_item_data (data_movimento),
    INDEX idx_conciliacao_item_status (status),
    INDEX idx_conciliacao_item_referencia (referencia_banco)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- COMERCIAL - ASSINATURA
-- =========================
CREATE TABLE IF NOT EXISTS catalogo_planos_comercial (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo_plano VARCHAR(30) NOT NULL,
    nome_exibicao VARCHAR(80) NOT NULL,
    versao_oferta INT NOT NULL DEFAULT 1,
    periodicidade VARCHAR(20) NOT NULL DEFAULT 'mensal',
    preco DECIMAL(10,2) NOT NULL,
    moeda VARCHAR(10) NOT NULL DEFAULT 'BRL',
    limite_usuarios INT NULL,
    recursos_json TEXT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    vigencia_inicio DATE NULL,
    vigencia_fim DATE NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalogo_plano_periodo_versao UNIQUE (codigo_plano, periodicidade, versao_oferta),
    INDEX idx_catalogo_plano (codigo_plano),
    INDEX idx_catalogo_periodicidade (periodicidade),
    INDEX idx_catalogo_ativo (ativo),
    INDEX idx_catalogo_versao (versao_oferta)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assinatura_empresa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    catalogo_plano_id INT NULL,
    plano_codigo VARCHAR(30) NOT NULL DEFAULT 'premium',
    ciclo_cobranca VARCHAR(20) NOT NULL DEFAULT 'mensal',
    status VARCHAR(20) NOT NULL DEFAULT 'trial',
    gateway VARCHAR(30) NOT NULL DEFAULT 'asaas',
    gateway_customer_id VARCHAR(120) NULL,
    gateway_subscription_id VARCHAR(120) NULL,
    data_inicio DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    data_renovacao DATE NULL,
    data_fim_trial DATE NULL,
    carencia_dias INT NOT NULL DEFAULT 7,
    data_limite_carencia DATE NULL,
    bloqueio_nivel VARCHAR(20) NOT NULL DEFAULT 'nenhum',
    bloqueado_desde DATETIME NULL,
    motivo_status VARCHAR(255) NULL,
    politica_efetivacao_dias INT NOT NULL DEFAULT 30,
    proximo_plano_codigo VARCHAR(30) NULL,
    mudanca_plano_solicitada_em DATETIME NULL,
    mudanca_plano_efetivar_em DATETIME NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_assinatura_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_assinatura_catalogo FOREIGN KEY (catalogo_plano_id) REFERENCES catalogo_planos_comercial(id),
    CONSTRAINT uq_assinatura_empresa UNIQUE (empresa_id),
    INDEX idx_assinatura_status (status),
    INDEX idx_assinatura_plano (plano_codigo),
    INDEX idx_assinatura_gateway_customer (gateway_customer_id),
    INDEX idx_assinatura_gateway_subscription (gateway_subscription_id),
    INDEX idx_assinatura_vencimento (data_vencimento),
    INDEX idx_assinatura_renovacao (data_renovacao),
    INDEX idx_assinatura_fim_trial (data_fim_trial),
    INDEX idx_assinatura_limite_carencia (data_limite_carencia),
    INDEX idx_assinatura_gateway (gateway),
    INDEX idx_assinatura_mudanca (mudanca_plano_efetivar_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cobranca_recorrente (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    assinatura_id INT NOT NULL,
    gateway VARCHAR(30) NOT NULL DEFAULT 'asaas',
    gateway_cobranca_id VARCHAR(120) NULL,
    referencia_interna VARCHAR(120) NOT NULL,
    competencia_ano INT NOT NULL,
    competencia_mes INT NOT NULL,
    periodicidade VARCHAR(20) NOT NULL DEFAULT 'mensal',
    valor_previsto DECIMAL(10,2) NOT NULL,
    valor_pago DECIMAL(10,2) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente',
    data_emissao DATE NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATETIME NULL,
    tentativas_pagamento INT NOT NULL DEFAULT 0,
    ultimo_erro VARCHAR(255) NULL,
    payload_gateway TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cobranca_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_cobranca_assinatura FOREIGN KEY (assinatura_id) REFERENCES assinatura_empresa(id),
    CONSTRAINT uq_cobranca_referencia UNIQUE (referencia_interna),
    CONSTRAINT uq_cobranca_gateway UNIQUE (gateway_cobranca_id),
    INDEX idx_cobranca_empresa (empresa_id),
    INDEX idx_cobranca_assinatura (assinatura_id),
    INDEX idx_cobranca_gateway (gateway),
    INDEX idx_cobranca_status (status),
    INDEX idx_cobranca_vencimento (data_vencimento),
    INDEX idx_cobranca_competencia (competencia_ano, competencia_mes),
    INDEX idx_cobranca_empresa_status_venc (empresa_id, status, data_vencimento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS evento_cobranca (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NULL,
    assinatura_id INT NULL,
    cobranca_id INT NULL,
    gateway VARCHAR(30) NOT NULL DEFAULT 'asaas',
    event_id_externo VARCHAR(150) NOT NULL,
    tipo_evento VARCHAR(80) NOT NULL,
    status_processamento VARCHAR(20) NOT NULL DEFAULT 'recebido',
    recebido_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processado_em DATETIME NULL,
    payload TEXT NULL,
    mensagem_erro VARCHAR(255) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_evento_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_evento_assinatura FOREIGN KEY (assinatura_id) REFERENCES assinatura_empresa(id),
    CONSTRAINT fk_evento_cobranca FOREIGN KEY (cobranca_id) REFERENCES cobranca_recorrente(id),
    CONSTRAINT uq_evento_gateway UNIQUE (gateway, event_id_externo),
    INDEX idx_evento_empresa (empresa_id),
    INDEX idx_evento_assinatura (assinatura_id),
    INDEX idx_evento_cobranca (cobranca_id),
    INDEX idx_evento_gateway (gateway),
    INDEX idx_evento_tipo (tipo_evento),
    INDEX idx_evento_status (status_processamento),
    INDEX idx_evento_recebido (recebido_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS historico_mudanca_plano (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    assinatura_id INT NOT NULL,
    plano_origem VARCHAR(30) NOT NULL,
    plano_destino VARCHAR(30) NOT NULL,
    tipo_mudanca VARCHAR(20) NOT NULL,
    regra_efetivacao VARCHAR(30) NOT NULL DEFAULT 'apos_30_dias',
    solicitado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    efetivado_em DATETIME NULL,
    solicitado_por_user_id INT NULL,
    executado_por_user_id INT NULL,
    observacoes TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_hist_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_hist_assinatura FOREIGN KEY (assinatura_id) REFERENCES assinatura_empresa(id),
    CONSTRAINT fk_hist_solicitado FOREIGN KEY (solicitado_por_user_id) REFERENCES users(id),
    CONSTRAINT fk_hist_executado FOREIGN KEY (executado_por_user_id) REFERENCES users(id),
    INDEX idx_hist_empresa (empresa_id),
    INDEX idx_hist_assinatura (assinatura_id),
    INDEX idx_hist_tipo (tipo_mudanca),
    INDEX idx_hist_solicitado (solicitado_em),
    INDEX idx_hist_efetivado (efetivado_em),
    INDEX idx_hist_solicitado_por (solicitado_por_user_id),
    INDEX idx_hist_executado_por (executado_por_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notificacao_comercial (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    assinatura_id INT NULL,
    tipo VARCHAR(50) NOT NULL,
    canal VARCHAR(20) NOT NULL DEFAULT 'email',
    destinatario VARCHAR(150) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente',
    agendada_para DATETIME NULL,
    enviada_em DATETIME NULL,
    tentativas INT NOT NULL DEFAULT 0,
    erro VARCHAR(255) NULL,
    payload TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_notif_assinatura FOREIGN KEY (assinatura_id) REFERENCES assinatura_empresa(id),
    INDEX idx_notif_empresa (empresa_id),
    INDEX idx_notif_assinatura (assinatura_id),
    INDEX idx_notif_tipo (tipo),
    INDEX idx_notif_status (status),
    INDEX idx_notif_agendada (agendada_para)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- COMERCIAL - OPERACIONAL
-- =========================
CREATE TABLE IF NOT EXISTS filiais (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    cnpj VARCHAR(18) NULL,
    endereco_rua VARCHAR(150) NULL,
    endereco_numero VARCHAR(10) NULL,
    endereco_bairro VARCHAR(100) NULL,
    endereco_cidade VARCHAR(100) NULL,
    endereco_uf VARCHAR(2) NULL,
    endereco_cep VARCHAR(8) NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_filial_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT uq_filial_empresa_codigo UNIQUE (empresa_id, codigo),
    INDEX idx_filial_empresa (empresa_id),
    INDEX idx_filial_codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    codigo_interno VARCHAR(50) NOT NULL,
    descricao_resumida VARCHAR(200) NOT NULL,
    descricao_completa TEXT NULL,
    unidade_medida VARCHAR(10) NULL,
    codigo_barras VARCHAR(60) NULL,
    gtin VARCHAR(60) NULL,
    ncm VARCHAR(10) NULL,
    ex_tipi VARCHAR(5) NULL,
    cest VARCHAR(10) NULL,
    ipi_classe VARCHAR(10) NULL,
    origem_mercadoria VARCHAR(20) NULL,
    tipo_item VARCHAR(20) NULL,
    controla_estoque TINYINT(1) NOT NULL DEFAULT 0,
    estoque_atual DECIMAL(15,3) NOT NULL DEFAULT 0.000,
    estoque_minimo DECIMAL(15,3) NOT NULL DEFAULT 0.000,
    valor_venda_padrao DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_custo DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_produto_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_produto_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT uq_produto_empresa_codigo UNIQUE (empresa_id, codigo_interno),
    INDEX idx_produto_empresa (empresa_id),
    INDEX idx_produto_filial (filial_id),
    INDEX idx_produto_ncm (empresa_id, ncm)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS servicos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    codigo_interno VARCHAR(50) NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    codigo_servico VARCHAR(20) NULL,
    nbs VARCHAR(20) NULL,
    natureza_servico VARCHAR(120) NULL,
    indicador_incidencia VARCHAR(30) NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_servico_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_servico_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT uq_servico_empresa_codigo UNIQUE (empresa_id, codigo_interno),
    INDEX idx_servico_empresa (empresa_id),
    INDEX idx_servico_filial (filial_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estoque_movimentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    produto_id INT NOT NULL,
    tipo_movimento VARCHAR(10) NOT NULL,
    quantidade DECIMAL(15,3) NOT NULL,
    valor_unitario DECIMAL(15,2) NULL,
    origem VARCHAR(20) NOT NULL DEFAULT 'manual',
    documento_ref VARCHAR(80) NULL,
    data_movimento DATE NOT NULL,
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_estoque_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_estoque_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_estoque_user FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_estoque_empresa (empresa_id),
    INDEX idx_estoque_filial (filial_id),
    INDEX idx_estoque_produto (produto_id),
    INDEX idx_estoque_data (data_movimento),
    INDEX idx_estoque_empresa_produto_data (empresa_id, produto_id, data_movimento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compras_nf_manual (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    fornecedor_id INT NOT NULL,
    lancamento_id INT NULL,
    numero_documento VARCHAR(50) NOT NULL,
    serie VARCHAR(10) NULL,
    data_emissao DATE NOT NULL,
    data_entrada DATE NOT NULL,
    valor_total DECIMAL(15,2) NOT NULL,
    observacoes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'registrada',
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_compra_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_compra_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_compra_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES entidades(id),
    CONSTRAINT fk_compra_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id),
    CONSTRAINT fk_compra_criado_por FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_compra_empresa (empresa_id),
    INDEX idx_compra_filial (filial_id),
    INDEX idx_compra_fornecedor (fornecedor_id),
    INDEX idx_compra_lancamento (lancamento_id),
    INDEX idx_compra_numero (numero_documento),
    INDEX idx_compra_emissao (data_emissao),
    INDEX idx_compra_entrada (data_entrada)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compras_nf_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    compra_id INT NOT NULL,
    produto_id INT NULL,
    descricao_livre VARCHAR(200) NULL,
    quantidade DECIMAL(15,3) NOT NULL,
    valor_unitario DECIMAL(15,2) NOT NULL,
    total_item DECIMAL(15,2) NOT NULL,
    ncm VARCHAR(10) NULL,
    cfop VARCHAR(10) NULL,
    cst VARCHAR(5) NULL,
    csosn VARCHAR(5) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_compra_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_compra_item_compra FOREIGN KEY (compra_id) REFERENCES compras_nf_manual(id) ON DELETE CASCADE,
    CONSTRAINT fk_compra_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    INDEX idx_compra_item_empresa (empresa_id),
    INDEX idx_compra_item_compra (compra_id),
    INDEX idx_compra_item_produto (produto_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS compras_nf_lancamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    compra_id INT NOT NULL,
    lancamento_id INT NOT NULL,
    parcela_numero INT NOT NULL,
    parcela_total INT NOT NULL,
    valor_parcela DECIMAL(15,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_compra_lanc_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_compra_lanc_compra FOREIGN KEY (compra_id) REFERENCES compras_nf_manual(id) ON DELETE CASCADE,
    CONSTRAINT fk_compra_lanc_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id),
    CONSTRAINT uq_compra_parcela UNIQUE (compra_id, parcela_numero),
    INDEX idx_compra_lanc_empresa (empresa_id),
    INDEX idx_compra_lanc_compra (compra_id),
    INDEX idx_compra_lanc_venc (data_vencimento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS documentos_venda (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    cliente_id INT NOT NULL,
    lancamento_id INT NULL,
    numero_documento VARCHAR(50) NOT NULL,
    data_emissao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE NULL,
    valor_total DECIMAL(15,2) NOT NULL,
    observacoes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'emitido',
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_doc_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_doc_cliente FOREIGN KEY (cliente_id) REFERENCES entidades(id),
    CONSTRAINT fk_doc_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id),
    CONSTRAINT fk_doc_criado_por FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_doc_empresa (empresa_id),
    INDEX idx_doc_filial (filial_id),
    INDEX idx_doc_cliente (cliente_id),
    INDEX idx_doc_lancamento (lancamento_id),
    INDEX idx_doc_numero (numero_documento),
    INDEX idx_doc_emissao (data_emissao),
    INDEX idx_doc_vencimento (data_vencimento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS documentos_venda_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    documento_id INT NOT NULL,
    tipo_item VARCHAR(1) NOT NULL,
    produto_id INT NULL,
    servico_id INT NULL,
    descricao VARCHAR(200) NULL,
    quantidade DECIMAL(15,3) NOT NULL,
    valor_unitario DECIMAL(15,2) NOT NULL,
    total_item DECIMAL(15,2) NOT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_doc_item_documento FOREIGN KEY (documento_id) REFERENCES documentos_venda(id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_doc_item_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    INDEX idx_doc_item_empresa (empresa_id),
    INDEX idx_doc_item_documento (documento_id),
    INDEX idx_doc_item_produto (produto_id),
    INDEX idx_doc_item_servico (servico_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- TABELAS DE PREÇO
-- =========================
CREATE TABLE IF NOT EXISTS tabelas_preco (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'venda',
    markup_padrao DECIMAL(5,2) DEFAULT 0.00,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_tabela_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT uq_tabela_empresa_codigo UNIQUE (empresa_id, codigo),
    INDEX idx_tabela_empresa (empresa_id),
    INDEX idx_tabela_codigo (codigo),
    INDEX idx_tabela_tipo (tipo),
    INDEX idx_tabela_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tabelas_preco_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    tabela_preco_id INT NOT NULL,
    produto_id INT NULL,
    servico_id INT NULL,
    preco_custo DECIMAL(15,4) DEFAULT 0.0000,
    preco_venda DECIMAL(15,4) NOT NULL,
    markup DECIMAL(5,2) DEFAULT 0.00,
    desconto_maximo DECIMAL(5,2) DEFAULT 0.00,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_tabela_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_tabela_item_tabela FOREIGN KEY (tabela_preco_id) REFERENCES tabelas_preco(id) ON DELETE CASCADE,
    CONSTRAINT fk_tabela_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_tabela_item_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    CONSTRAINT uq_tabela_item_produto_servico UNIQUE (tabela_preco_id, produto_id, servico_id),
    INDEX idx_tabela_item_empresa (empresa_id),
    INDEX idx_tabela_item_tabela (tabela_preco_id),
    INDEX idx_tabela_item_produto (produto_id),
    INDEX idx_tabela_item_servico (servico_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- ORÇAMENTOS
-- =========================
CREATE TABLE IF NOT EXISTS orcamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    numero VARCHAR(30) NOT NULL,
    serie VARCHAR(10) DEFAULT '1',
    cliente_id INT NOT NULL,
    vendedor_id INT NULL,
    data_emissao DATE NOT NULL,
    data_validade DATE NOT NULL,
    data_aprovacao DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'emitido',
    tabela_preco_id INT NULL,
    valor_produtos DECIMAL(15,2) DEFAULT 0.00,
    valor_servicos DECIMAL(15,2) DEFAULT 0.00,
    valor_desconto DECIMAL(15,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL,
    observacoes TEXT NULL,
    observacoes_internas TEXT NULL,
    pedido_id INT NULL,
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_orcamento_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_orcamento_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_orcamento_cliente FOREIGN KEY (cliente_id) REFERENCES entidades(id),
    CONSTRAINT fk_orcamento_vendedor FOREIGN KEY (vendedor_id) REFERENCES entidades(id),
    CONSTRAINT fk_orcamento_tabela FOREIGN KEY (tabela_preco_id) REFERENCES tabelas_preco(id),
    CONSTRAINT fk_orcamento_criado_por FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_orcamento_empresa_status (empresa_id, status),
    INDEX idx_orcamento_cliente (cliente_id),
    INDEX idx_orcamento_data (data_emissao),
    INDEX idx_orcamento_numero (numero)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orcamentos_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    orcamento_id INT NOT NULL,
    tipo_item VARCHAR(1) NOT NULL,
    produto_id INT NULL,
    servico_id INT NULL,
    descricao VARCHAR(200) NOT NULL,
    quantidade DECIMAL(15,3) NOT NULL,
    valor_unitario DECIMAL(15,4) NOT NULL,
    valor_desconto DECIMAL(15,4) DEFAULT 0.0000,
    percentual_desconto DECIMAL(5,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_orcamento_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_orcamento_item_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamentos(id) ON DELETE CASCADE,
    CONSTRAINT fk_orcamento_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_orcamento_item_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    INDEX idx_orcamento_item_empresa (empresa_id),
    INDEX idx_orcamento_item_orcamento (orcamento_id),
    INDEX idx_orcamento_item_produto (produto_id),
    INDEX idx_orcamento_item_servico (servico_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- PEDIDOS DE VENDA
-- =========================
CREATE TABLE IF NOT EXISTS pedidos_venda (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    numero VARCHAR(30) NOT NULL,
    serie VARCHAR(10) DEFAULT '1',
    orcamento_id INT NULL,
    cliente_id INT NOT NULL,
    vendedor_id INT NULL,
    data_emissao DATE NOT NULL,
    data_entrega DATE NULL,
    data_faturamento DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aprovado',
    valor_produtos DECIMAL(15,2) DEFAULT 0.00,
    valor_servicos DECIMAL(15,2) DEFAULT 0.00,
    valor_desconto DECIMAL(15,2) DEFAULT 0.00,
    valor_frete DECIMAL(15,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL,
    observacoes TEXT NULL,
    observacoes_faturamento TEXT NULL,
    documento_venda_id INT NULL,
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_pedido_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_pedido_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamentos(id),
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES entidades(id),
    CONSTRAINT fk_pedido_vendedor FOREIGN KEY (vendedor_id) REFERENCES entidades(id),
    CONSTRAINT fk_pedido_documento FOREIGN KEY (documento_venda_id) REFERENCES documentos_venda(id),
    CONSTRAINT fk_pedido_criado_por FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_pedido_empresa_status (empresa_id, status),
    INDEX idx_pedido_cliente (cliente_id),
    INDEX idx_pedido_orcamento (orcamento_id),
    INDEX idx_pedido_data (data_emissao),
    INDEX idx_pedido_numero (numero)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pedidos_venda_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    pedido_id INT NOT NULL,
    orcamento_item_id INT NULL,
    tipo_item VARCHAR(1) NOT NULL,
    produto_id INT NULL,
    servico_id INT NULL,
    descricao VARCHAR(200) NOT NULL,
    quantidade DECIMAL(15,3) NOT NULL,
    quantidade_atendida DECIMAL(15,3) DEFAULT 0.000,
    valor_unitario DECIMAL(15,4) NOT NULL,
    valor_desconto DECIMAL(15,4) DEFAULT 0.0000,
    percentual_desconto DECIMAL(5,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_pedido_item_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos_venda(id) ON DELETE CASCADE,
    CONSTRAINT fk_pedido_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_pedido_item_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    INDEX idx_pedido_item_empresa (empresa_id),
    INDEX idx_pedido_item_pedido (pedido_id),
    INDEX idx_pedido_item_produto (produto_id),
    INDEX idx_pedido_item_servico (servico_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================
-- PDV / CAIXA
-- =========================
CREATE TABLE IF NOT EXISTS pdv_sessoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    user_id INT NOT NULL,
    numero VARCHAR(20) NOT NULL,
    pdv_nome VARCHAR(50) DEFAULT 'PDV Principal',
    data_abertura DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fechamento DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'aberto',
    valor_abertura DECIMAL(15,2) DEFAULT 0.00,
    valor_vendas DECIMAL(15,2) DEFAULT 0.00,
    valor_sangria DECIMAL(15,2) DEFAULT 0.00,
    valor_suprimento DECIMAL(15,2) DEFAULT 0.00,
    valor_fechamento DECIMAL(15,2) NULL,
    observacoes TEXT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pdv_sessao_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_pdv_sessao_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_pdv_sessao_user FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_pdv_empresa_status (empresa_id, status),
    INDEX idx_pdv_usuario (user_id),
    INDEX idx_pdv_data_abertura (data_abertura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pdv_vendas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    filial_id INT NULL,
    sessao_id INT NOT NULL,
    numero VARCHAR(30) NOT NULL,
    cliente_id INT NULL,
    data_venda DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'em_andamento',
    subtotal DECIMAL(15,2) DEFAULT 0.00,
    valor_desconto DECIMAL(15,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL,
    valor_dinheiro DECIMAL(15,2) DEFAULT 0.00,
    valor_cartao_credito DECIMAL(15,2) DEFAULT 0.00,
    valor_cartao_debito DECIMAL(15,2) DEFAULT 0.00,
    valor_pix DECIMAL(15,2) DEFAULT 0.00,
    valor_boleto DECIMAL(15,2) DEFAULT 0.00,
    valor_outros DECIMAL(15,2) DEFAULT 0.00,
    valor_recebido DECIMAL(15,2) DEFAULT 0.00,
    valor_troco DECIMAL(15,2) DEFAULT 0.00,
    chave_cupom VARCHAR(50) NULL,
    numero_cupom VARCHAR(20) NULL,
    situacao_cupom VARCHAR(20) DEFAULT 'pendente',
    observacoes TEXT NULL,
    documento_venda_id INT NULL,
    criado_por_user_id INT NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pdv_venda_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_pdv_venda_filial FOREIGN KEY (filial_id) REFERENCES filiais(id),
    CONSTRAINT fk_pdv_venda_sessao FOREIGN KEY (sessao_id) REFERENCES pdv_sessoes(id),
    CONSTRAINT fk_pdv_venda_cliente FOREIGN KEY (cliente_id) REFERENCES entidades(id),
    CONSTRAINT fk_pdv_venda_documento FOREIGN KEY (documento_venda_id) REFERENCES documentos_venda(id),
    CONSTRAINT fk_pdv_venda_criado_por FOREIGN KEY (criado_por_user_id) REFERENCES users(id),
    INDEX idx_pdv_venda_empresa_data (empresa_id, data_venda),
    INDEX idx_pdv_venda_sessao (sessao_id),
    INDEX idx_pdv_venda_cliente (cliente_id),
    INDEX idx_pdv_venda_numero (numero),
    INDEX idx_pdv_venda_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pdv_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    venda_id INT NOT NULL,
    sequencia INT NOT NULL DEFAULT 1,
    tipo_item VARCHAR(1) NOT NULL,
    produto_id INT NULL,
    servico_id INT NULL,
    codigo VARCHAR(50) NULL,
    descricao VARCHAR(200) NOT NULL,
    quantidade DECIMAL(15,3) NOT NULL,
    valor_unitario DECIMAL(15,4) NOT NULL,
    valor_desconto DECIMAL(15,4) DEFAULT 0.0000,
    percentual_desconto DECIMAL(5,2) DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL,
    codigo_barras VARCHAR(60) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pdv_item_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_pdv_item_venda FOREIGN KEY (venda_id) REFERENCES pdv_vendas(id) ON DELETE CASCADE,
    CONSTRAINT fk_pdv_item_produto FOREIGN KEY (produto_id) REFERENCES produtos(id),
    CONSTRAINT fk_pdv_item_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    INDEX idx_pdv_item_empresa (empresa_id),
    INDEX idx_pdv_item_venda (venda_id),
    INDEX idx_pdv_item_produto (produto_id),
    INDEX idx_pdv_item_servico (servico_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
