-- MIGRAÇÃO: tabelas do módulo NFS-e Nacional

CREATE TABLE IF NOT EXISTS nfse_nacional_configuracoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    ambiente VARCHAR(20) NOT NULL DEFAULT 'homologacao',
    inscricao_municipal VARCHAR(30) NULL,
    codigo_municipio VARCHAR(10) NULL,
    regime_tributario VARCHAR(50) NULL,
    serie VARCHAR(20) DEFAULT '1',
    versao_layout VARCHAR(30) DEFAULT '1.0',
    endpoint_base VARCHAR(255) NULL,
    emissor_ativo BOOLEAN DEFAULT TRUE,
    observacoes TEXT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_nfse_config_empresa_ambiente (empresa_id, ambiente),
    KEY idx_nfse_config_empresa (empresa_id),
    CONSTRAINT fk_nfse_config_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfse_nacional_certificados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    ambiente VARCHAR(20) NOT NULL DEFAULT 'homologacao',
    arquivo_nome VARCHAR(255) NOT NULL,
    caminho_arquivo VARCHAR(255) NULL,
    validade_em DATE NULL,
    ativo BOOLEAN DEFAULT TRUE,
    observacoes TEXT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_nfse_cert_empresa_ambiente_arquivo (empresa_id, ambiente, arquivo_nome),
    KEY idx_nfse_cert_empresa (empresa_id),
    KEY idx_nfse_cert_validade (validade_em),
    CONSTRAINT fk_nfse_cert_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfse_nacional_integracoes_origem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    origem_tipo VARCHAR(40) NOT NULL,
    origem_id VARCHAR(80) NULL,
    origem_referencia VARCHAR(120) NULL,
    canal_origem VARCHAR(40) NOT NULL DEFAULT 'manual',
    payload_origem LONGTEXT NULL,
    hash_idempotencia VARCHAR(80) NOT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_nfse_origem_empresa_tipo_id_canal (empresa_id, origem_tipo, origem_id, canal_origem),
    KEY idx_nfse_origem_empresa (empresa_id),
    KEY idx_nfse_origem_hash (hash_idempotencia),
    CONSTRAINT fk_nfse_origem_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfse_nacional_emissoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    configuracao_id INT NULL,
    certificado_id INT NULL,
    tomador_id INT NOT NULL,
    servico_id INT NOT NULL,
    integracao_origem_id INT NULL,
    lancamento_id INT NULL,
    ambiente VARCHAR(20) NOT NULL DEFAULT 'homologacao',
    numero_interno VARCHAR(50) NOT NULL,
    numero_nfse VARCHAR(30) NULL,
    chave_nfse VARCHAR(120) NULL,
    codigo_verificacao VARCHAR(40) NULL,
    protocolo VARCHAR(80) NULL,
    status_processamento VARCHAR(30) NOT NULL DEFAULT 'RASCUNHO',
    situacao_fiscal VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
    valor_servico DECIMAL(15,2) NOT NULL,
    valor_deducoes DECIMAL(15,2) DEFAULT 0.00,
    valor_iss DECIMAL(15,2) DEFAULT 0.00,
    servico_local_prestacao VARCHAR(20) NOT NULL DEFAULT 'emitente',
    tp_ret_issqn VARCHAR(2) NOT NULL DEFAULT '1',
    observacoes TEXT NULL,
    xml_dps LONGTEXT NULL,
    xml_nfse LONGTEXT NULL,
    payload_envio LONGTEXT NULL,
    payload_retorno LONGTEXT NULL,
    log_tecnico LONGTEXT NULL,
    erro_retorno LONGTEXT NULL,
    hash_idempotencia VARCHAR(80) NOT NULL,
    versao_layout VARCHAR(30) DEFAULT '1.0',
    versao_xsd VARCHAR(30) DEFAULT '1.0',
    origem_tipo VARCHAR(40) NOT NULL DEFAULT 'MANUAL',
    origem_referencia VARCHAR(120) NULL,
    canal_origem VARCHAR(40) NOT NULL DEFAULT 'manual',
    criado_por_user_id INT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_nfse_emissao_empresa_hash (empresa_id, hash_idempotencia),
    UNIQUE KEY uq_nfse_emissao_empresa_numero_interno (empresa_id, numero_interno),
    KEY idx_nfse_emissao_empresa_status (empresa_id, status_processamento),
    KEY idx_nfse_emissao_empresa_nfse (empresa_id, numero_nfse),
    KEY idx_nfse_emissao_tomador (tomador_id),
    KEY idx_nfse_emissao_servico (servico_id),
    CONSTRAINT fk_nfse_emissao_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_nfse_emissao_config FOREIGN KEY (configuracao_id) REFERENCES nfse_nacional_configuracoes(id),
    CONSTRAINT fk_nfse_emissao_cert FOREIGN KEY (certificado_id) REFERENCES nfse_nacional_certificados(id),
    CONSTRAINT fk_nfse_emissao_tomador FOREIGN KEY (tomador_id) REFERENCES entidades(id),
    CONSTRAINT fk_nfse_emissao_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    CONSTRAINT fk_nfse_emissao_origem FOREIGN KEY (integracao_origem_id) REFERENCES nfse_nacional_integracoes_origem(id),
    CONSTRAINT fk_nfse_emissao_lancamento FOREIGN KEY (lancamento_id) REFERENCES lancamentos(id),
    CONSTRAINT fk_nfse_emissao_user FOREIGN KEY (criado_por_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfse_nacional_fila (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    emissao_id INT NOT NULL,
    status_fila VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
    tentativas INT NOT NULL DEFAULT 0,
    proxima_tentativa_em DATETIME NULL,
    ultimo_erro LONGTEXT NULL,
    payload LONGTEXT NULL,
    processado_em DATETIME NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_nfse_fila_empresa_emissao (empresa_id, emissao_id),
    KEY idx_nfse_fila_empresa_status (empresa_id, status_fila),
    CONSTRAINT fk_nfse_fila_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_nfse_fila_emissao FOREIGN KEY (emissao_id) REFERENCES nfse_nacional_emissoes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nfse_nacional_eventos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    emissao_id INT NOT NULL,
    tipo_evento VARCHAR(40) NOT NULL,
    status_evento VARCHAR(30) NOT NULL DEFAULT 'registrado',
    protocolo VARCHAR(80) NULL,
    mensagem LONGTEXT NULL,
    payload_envio LONGTEXT NULL,
    payload_retorno LONGTEXT NULL,
    criado_por_user_id INT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_nfse_evento_empresa_tipo (empresa_id, tipo_evento),
    KEY idx_nfse_evento_emissao (emissao_id),
    CONSTRAINT fk_nfse_evento_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id),
    CONSTRAINT fk_nfse_evento_emissao FOREIGN KEY (emissao_id) REFERENCES nfse_nacional_emissoes(id) ON DELETE CASCADE,
    CONSTRAINT fk_nfse_evento_user FOREIGN KEY (criado_por_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;