-- Migração de dados do Rio de Janeiro (códigos principais) para nfse_ctrib_mun_referencia
-- Código IBGE do Rio de Janeiro: 3304557
-- Códigos principais extraídos de Anexos/TabelaServicos.txt

INSERT INTO nfse_ctrib_mun_referencia (
    codigo_ibge,
    uf_sigla,
    nome_municipio,
    codigo_tributacao_municipal,
    descricao,
    exige_ctribmun,
    data_inicio_vigencia,
    origem_catalogo,
    ativo,
    criado_em,
    atualizado_em
) VALUES
('3304557', 'RJ', 'Rio de Janeiro', '01', 'Serviços de informática e congêneres.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.01', 'Análise e desenvolvimento de sistemas.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.01.01', 'Análise de sistemas,', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.01.02', 'Desenvolvimento de sistemas', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.01.04', 'Geração de programa de computador sob encomenda', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.02', 'Programação.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.02.01', 'Programação', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03', 'Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.02', 'Provimento de acesso à internet', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.03', 'Provimento de voz sobre internet', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.04', 'Provimento de conteúdo para a internet', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.05', 'Provimento de serviço de aplicação', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.07', 'Serviços de data center, parque tecnológico ou congêneres', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.08', 'Processamento de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos ou sistemas de informação, entre outros formatos, e congêneres', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.03.09', 'Armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos ou sistemas de informação, entre outros formatos, e congêneres', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.04', 'Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado, incluindo tablets, smartphones e congêneres.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.04.01', 'Elaboração de programa de computadores', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.04.02', 'Elaboração de jogo eletrônico', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.04.03', 'Elaboração de programa de computador sob encomenda, não derivado de software preexistente, cujo desenvolvimento se dê integralmente no Brasil e cujos direitos autorais permaneçam reservados ao contratante do serviço, desde que atendidos os demais requisitos previstos no art. 8º da Instrução Normativa SMF nº 16, de 02 de julho de 2012', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.05', 'Licenciamento ou cessão de direito de uso de programas de computação.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.05.01', 'Licenciamento de uso de programa de computação', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.05.02', 'Cessão de direito de uso de programa de computação', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.06', 'Assessoria e consultoria em informática.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.06.01', 'Assessoria ou consultoria em informática', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.07', 'Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.07.01', 'Suporte técnico em informática', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.07.02', 'Instalação e/ou configuração de programa de computação e/ou banco de dados', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.07.03', 'Manutenção de programa de computação e/ou banco de dados', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.07.04', 'Customização de programa de computador', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.07.05', 'Atualização de software', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.08', 'Planejamento, confecção, manutenção e atualização de páginas eletrônicas.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.08.01', 'Projeto de páginas eletrônicas', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.08.02', 'Confecção ou desenvolvimento de páginas eletrônicas', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.08.03', 'Manutenção e/ou atualização de páginas eletrônicas', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.09', 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos (exceto a distribuição de conteúdos pelas prestadoras de Serviço de Acesso Condicionado, de que trata a Lei no 12.485, de 12 de setembro de 2011, sujeita ao ICMS).', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.09.01', 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem ou texto por meio da internet, para pessoas jurídicas', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '01.09.02', 'Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem ou texto por meio da internet, para pessoas naturais', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02', 'Serviços de pesquisas e desenvolvimento de qualquer natureza.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02.01', 'Serviços de pesquisas e desenvolvimento de qualquer natureza.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02.01.01', 'Pesquisa e desenvolvimento (P&D)', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02.01.02', 'Pesquisa de mercado ou de opinião pública', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02.01.03', 'Pesquisa de opinião pública', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02.01.04', 'Pesquisa de mercado', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '02.01.05', 'Desenvolvimento de projetos de créditos de carbono', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03', 'Serviços prestados mediante locação, cessão de direito de uso e congêneres.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03.02', 'Cessão de direito de uso de marcas e de sinais de propaganda.', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03.02.01', 'Cessão de direito de uso de sinais de propaganda', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03.02.02', 'Cessão de direito de uso de marca', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03.02.04', 'Serviços relativos à indústria cinematográfica, correspondentes a receitas de licenciamento para exibição da obra cinematográfica, exclusivamente vinculados a filme brasileiro, natural ou de enredo', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03.02.05', 'Serviços relativos à indústria cinematográfica, correspondentes a receitas de licenciamento para exibição da obra cinematográfica, vinculados a filme estrangeiro', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW()),
('3304557', 'RJ', 'Rio de Janeiro', '03.02.06', 'Serviços prestados mediante locação, cessão de direito de uso e congêneres, não especificados em outros códigos, exceto locação de bens móveis pura e simples, nos termos da Instrução Normativa SMF Nº 15, de 12/01/2012', TRUE, NULL, 'TabelaServicos_RJ', TRUE, NOW(), NOW())
ON DUPLICATE KEY UPDATE 
    descricao = VALUES(descricao),
    exige_ctribmun = VALUES(exige_ctribmun),
    atualizado_em = NOW();
