-- Verificar tamanho máximo dos códigos em CTISS_BH
SELECT MAX(LENGTH(ETM_CDTRIBUTACAO)) as max_codigo_length, 
       ETM_CDTRIBUTACAO 
FROM CTISS_BH 
WHERE ETM_CDTRIBUTACAO IS NOT NULL 
GROUP BY ETM_CDTRIBUTACAO 
ORDER BY LENGTH(ETM_CDTRIBUTACAO) DESC 
LIMIT 5;
